### ISSUE TITLE
[Bug, minor] For previously added servers, `Enable logging in as a public user` checkbox state is not remembered when using `Browse...`

### ISSUE THREAD

**Issue by psobolewskiPhD** [qupath/qupath-extension-omero#4]
When adding a server, I can uncheck `Enable logging in as a public user` and directly get a login window.
But if I want to return to that server later using `Browser server...` it logs me in as public.
I'd prefer if the setting was honored so it would prompt a login each time and take me to the right stuff right away.
It's not intuitive that I need to go to `Manage server connections` to log in (see also https://github.com/qupath/qupath-extension-omero/issues/3 )

**Comment by Rylern** [comment]
Thanks, it should have been addressed in the [v0.1.0-rc2 release](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc2). Can you see if that version fixes the issue?

**Comment by psobolewskiPhD** [comment]
I think the current solution is better?
What I find is that if I uncheck `enable public` when making the server I just want that to be set and stored.
Currently when I re-access the server I get:
![image](https://github.com/qupath/qupath-extension-omero/assets/76622105/e248a59b-6aa6-4751-bf38-aa48b3539c56)

and then I have to *again* uncheck `enable public` to get my stuff--each and every time.

Maybe that setting could be moved to and stored under `Manage servers`? So if it's unchecked you get a login prompt and if it's checked you get the public?

**Comment by psobolewskiPhD** [comment]
I think the current solution is better?
What I find is that if I uncheck `enable public` when making the server I just want that to be set and stored.
Currently when I re-access the server I get:
![image](https://github.com/qupath/qupath-extension-omero/assets/76622105/e248a59b-6aa6-4751-bf38-aa48b3539c56)

and then I have to *again* uncheck `enable public` to get my stuff--each and every time.

Maybe that setting could be moved to and stored under `Manage servers`? So if it's unchecked you get a login prompt and if it's checked you get the public?

**Comment by Rylern** [comment]
> Maybe that setting could be moved to and stored under Manage servers? So if it's unchecked you get a login prompt and if it's checked you get the public?

That's a good idea, I implemented that in the [v0.1.0-rc3 release](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc3)

**Comment by psobolewskiPhD** [comment]
Works nice now. If I don't enable public then with each subsequent session I immediately go into the login prompt.
And the ui in manage servers looks good to me, works nicely.
